/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window.vue;

import bataille_navale.Jeu;
import bataille_navale.Partie;
import bataille_navale.Profil;
import java.awt.GridLayout;
import window.main.BatailleNavale;

/**
 * VuePartie
 * @author Tristan
 */
public class VuePartie extends javax.swing.JFrame {
    
    
    /////////////////////////////// VARIABLES /////////////////////////////////
    
    
    public BatailleNavale _batailleNavale;
    public Jeu _jeu;
    public Profil _profil;
    public Partie _partie;
    
    
    ///////////////////////////// CONSTRUCTEUR ////////////////////////////////

    
    /**
     * Creates new form VuePartie
     * @param batailleNavale Fenetre d'accueil
     * @param jeu main
     * @param profil profil du joueur qui joue la partie
     * @param partie partie jouee par le joueur
     */
    public VuePartie(BatailleNavale batailleNavale, Jeu jeu, Profil profil, Partie partie) {
        initComponents();
        
        this._batailleNavale = batailleNavale;
        this._jeu = jeu;
        this._profil = profil;
        this._partie = partie;
        
        this.initialisation();
        this.popupQuitterPartie.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        
    } // VuePartie(BatailleNavale batailleNavale, Jeu jeu, Profil profil, Partie partie)
    
    
    /////////////////////////////// FONCTIONS /////////////////////////////////
    
    
    /**
     * Permet d'initialiser la partie
     */
    public void initialisation() {
        
        // Initialisation des instructions et des epoques
        this.labelEpoque.setText(this._partie.getParametre().getEpoque().getNom());
        this.labelInstructions.setText("À vous de jouer ! Cliquez sur une case de la grille adverse.");
        
        // Initialisation des deux grilles de jeu
        GridLayout gl = new GridLayout(this._partie.getParametre().getNbCaseX(),this._partie.getParametre().getNbCaseY());
        gl.setHgap(0);
        gl.setVgap(0);
        this.plateauJoueurAdverse.setLayout(gl);
        this.plateauJoueurCourant.setLayout(gl);
        
        int numC = 0;
        for(int i=0;i<this._partie.getParametre().getNbCaseX();i++) {
            for(int j=0;j<this._partie.getParametre().getNbCaseY();j++) {
                
                this.plateauJoueurCourant.add(this._partie.getJ1().getCases().get(numC));
                this.plateauJoueurAdverse.add(this._partie.getJ2().getCases().get(numC));
                numC++;
                
            }
        }
        
    } // initialisation()
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupQuitterPartie = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        labelEpoque = new javax.swing.JLabel();
        labelInstructions = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        plateauJoueurAdverse = new javax.swing.JPanel();
        plateauJoueurCourant = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        popupQuitterPartie.setResizable(false);
        popupQuitterPartie.setSize(new java.awt.Dimension(500, 180));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Êtes-vous sûr de vouloir quitter la partie ?");

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Nouvelle partie");

        jButton4.setText("Enregistrer et quitter");

        jButton5.setText("Quitter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popupQuitterPartieLayout = new javax.swing.GroupLayout(popupQuitterPartie.getContentPane());
        popupQuitterPartie.getContentPane().setLayout(popupQuitterPartieLayout);
        popupQuitterPartieLayout.setHorizontalGroup(
            popupQuitterPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupQuitterPartieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(popupQuitterPartieLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(popupQuitterPartieLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        popupQuitterPartieLayout.setVerticalGroup(
            popupQuitterPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupQuitterPartieLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(popupQuitterPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelEpoque.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelEpoque.setForeground(new java.awt.Color(51, 102, 255));
        labelEpoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEpoque.setText("Epoque");
        labelEpoque.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelInstructions.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelInstructions.setForeground(new java.awt.Color(102, 153, 255));
        labelInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInstructions.setText("Instruction");

        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        plateauJoueurAdverse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        plateauJoueurAdverse.setMaximumSize(new java.awt.Dimension(500, 500));
        plateauJoueurAdverse.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout plateauJoueurAdverseLayout = new javax.swing.GroupLayout(plateauJoueurAdverse);
        plateauJoueurAdverse.setLayout(plateauJoueurAdverseLayout);
        plateauJoueurAdverseLayout.setHorizontalGroup(
            plateauJoueurAdverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        plateauJoueurAdverseLayout.setVerticalGroup(
            plateauJoueurAdverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        plateauJoueurCourant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        plateauJoueurCourant.setMaximumSize(new java.awt.Dimension(300, 300));
        plateauJoueurCourant.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout plateauJoueurCourantLayout = new javax.swing.GroupLayout(plateauJoueurCourant);
        plateauJoueurCourant.setLayout(plateauJoueurCourantLayout);
        plateauJoueurCourantLayout.setHorizontalGroup(
            plateauJoueurCourantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        plateauJoueurCourantLayout.setVerticalGroup(
            plateauJoueurCourantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Battleship");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Époque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plateauJoueurAdverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEpoque, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plateauJoueurCourant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEpoque, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plateauJoueurCourant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(plateauJoueurAdverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /******************* JDIALOG - GESTION DE LA PARTIE **********************/
    
    
    /**
     * Permet d'afficher les options pour quitter la partie
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setEnabled(false);
        this.popupQuitterPartie.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * Permet de quitter definitivement la partie
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        this._batailleNavale.setEnabled(true);
        this._batailleNavale.setVisible(true);
        this.setVisible(false);
        this.setEnabled(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    /**
     * Permet de revenir a la partie
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.setEnabled(true);
        this.popupQuitterPartie.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEpoque;
    private javax.swing.JLabel labelInstructions;
    private javax.swing.JPanel plateauJoueurAdverse;
    private javax.swing.JPanel plateauJoueurCourant;
    private javax.swing.JDialog popupQuitterPartie;
    // End of variables declaration//GEN-END:variables


} // class VuePartie
