/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window.main;

import bataille_navale.Jeu;
import bataille_navale.Profil;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.Iterator;
import javax.swing.JButton;
import stockage.DAOFactory;

/**
 * BatailleNavale
 * @author Tristan
 */
public class BatailleNavale extends javax.swing.JFrame {
    
    
    /////////////////////////////// VARIABLES /////////////////////////////////
    
    
    protected Jeu _jeu;
    static int w = 800;
    static int h = 600;
    
    
    ///////////////////////////// CONSTRUCTEUR ////////////////////////////////
    
    
    /**
     * Creates new form BatailleNavale
     */
    public BatailleNavale() {
        initComponents();
        
        this._jeu = new Jeu();
        this.initialisation();
        this.setLocationRelativeTo(null);
        
    } // BatailleNavale()
    
    
    /////////////////////////////// FONCTIONS /////////////////////////////////
    
    
    /**
     * Permet d'intialiser le jeu a partir des fichier de configuration
     * et de sauvegarde
     */
    public void initialisation() {
        
        if(DAOFactory.getInstance().getDAO_Sauvegarde().getAllProfils() == null 
                || DAOFactory.getInstance().getDAO_Sauvegarde().getAllProfils().isEmpty()) {
            System.out.println(DAOFactory.getInstance().getDAO_Sauvegarde().getAllProfils().size());
            
            this.jLabel5.setVisible(true);
            
        } else {
            
            // Masque le label qui signal qu'aucun profil n'est disponible
            this.jLabel5.setVisible(false);
            // Affichage des profils disponibles
            int nbProfils = DAOFactory.getInstance().getDAO_Sauvegarde().getAllProfils().size();
            FlowLayout fl = new FlowLayout();
            this.listeProfils.setPreferredSize(new Dimension(w,h/2));
            this.listeProfils.setLayout(fl);
            
            Iterator iterator = DAOFactory.getInstance().getDAO_Sauvegarde()
                        .getAllProfils().keySet().iterator();
            while(iterator.hasNext()) {
                
                JButton profil = new JButton(((Profil)DAOFactory.getInstance().getDAO_Sauvegarde()
                        .getAllProfils().get(iterator.next())).getNom());
                profil.setPreferredSize(new Dimension(w/(nbProfils+1),h/2-5));
                this.listeProfils.add(profil);
                
            }
            
        }
        
    } // initialisation()

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupNouveauProfil = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        saisieNomProfil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        erreurNomProfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        listeProfils = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        popupNouveauProfil.setMinimumSize(new java.awt.Dimension(400, 220));
        popupNouveauProfil.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nouveau nom de profil");

        saisieNomProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieNomProfilActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Nom");

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton2.setText("Ajouter le profil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        erreurNomProfil.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        erreurNomProfil.setForeground(new java.awt.Color(255, 102, 102));
        erreurNomProfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erreurNomProfil.setText("Désolé, ce nom de profil est déjà utilisé.");

        javax.swing.GroupLayout popupNouveauProfilLayout = new javax.swing.GroupLayout(popupNouveauProfil.getContentPane());
        popupNouveauProfil.getContentPane().setLayout(popupNouveauProfilLayout);
        popupNouveauProfilLayout.setHorizontalGroup(
            popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                .addGroup(popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                        .addGroup(popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saisieNomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jButton2)))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(erreurNomProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        popupNouveauProfilLayout.setVerticalGroup(
            popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupNouveauProfilLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(popupNouveauProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saisieNomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erreurNomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Battleship");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Devenez le maître des océans !");

        jButton1.setText("Ajouter un profil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aucun profil disponible");

        javax.swing.GroupLayout listeProfilsLayout = new javax.swing.GroupLayout(listeProfils);
        listeProfils.setLayout(listeProfilsLayout);
        listeProfilsLayout.setHorizontalGroup(
            listeProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        listeProfilsLayout.setVerticalGroup(
            listeProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeProfilsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(listeProfils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(listeProfils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Permet d'afficher la fenetre permettant de creer un nouveau profil
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.popupNouveauProfil.setLocationRelativeTo(null);
        this.erreurNomProfil.setVisible(false);
        this.popupNouveauProfil.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /********************* JDIALOG - NOUVEAU PROFIL **************************/
    
    
    /**
     * Zone de saisie du nouveau profil
     * @param evt 
     */
    private void saisieNomProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieNomProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saisieNomProfilActionPerformed

    
    
    /**
     * Permet d'ajouter le nouveau profil
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
      if(DAOFactory.getInstance().getDAO_Sauvegarde().isExistingProfil(this.saisieNomProfil.getText())) {
          
          // Affichage du message d'erreur
          this.erreurNomProfil.setVisible(true);
          
      } else {
          
          // Creation et sauvegrade du profil
          Profil newProfil = new Profil(this.saisieNomProfil.getText());
          DAOFactory.getInstance().getDAO_Sauvegarde().saveProfil(newProfil);
          
      }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /******************************* MAIN ************************************/ 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatailleNavale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatailleNavale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatailleNavale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatailleNavale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatailleNavale().setVisible(true);
            }
        });
        
    } // main(String args[])
    
    
    //////////////////////// VARIABLES GRAPHIQUES /////////////////////////////
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erreurNomProfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel listeProfils;
    private javax.swing.JDialog popupNouveauProfil;
    private javax.swing.JTextField saisieNomProfil;
    // End of variables declaration//GEN-END:variables


} // class BatailleNavale
